[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
nodaemon=true

[program:redis-cluster-master-0]
command=/usr/local/bin/redis-server /etc/redis/redis.conf --protected-mode no --bind 0.0.0.0 --port 6380 --cluster-config-file 6380.conf --dbfilename dump-6380.rdb --appendfilename aof.6380.base.rdb
autostart=true
autorestart=true
priority=100
stdout_logfile=/var/log/redis/redis-cluster-master-0.out.log
stderr_logfile=/var/log/redis/redis-cluster-master-0.err.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stopsignal=TERM

[program:redis-cluster-master-1]
command=/usr/local/bin/redis-server /etc/redis/redis.conf --protected-mode no --bind 0.0.0.0 --port 6381 --cluster-config-file 6381.conf --dbfilename dump-6381.rdb --appendfilename aof.6381.base.rdb
autostart=true
autorestart=true
priority=101
stdout_logfile=/var/log/redis/redis-cluster-master-1.out.log
stderr_logfile=/var/log/redis/redis-cluster-master-1.err.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stopsignal=TERM

[program:redis-cluster-master-2]
command=/usr/local/bin/redis-server /etc/redis/redis.conf --protected-mode no --bind 0.0.0.0 --port 6382 --cluster-config-file 6382.conf --dbfilename dump-6382.rdb --appendfilename aof.6382.base.rdb
autostart=true
autorestart=true
priority=102
stdout_logfile=/var/log/redis/redis-cluster-master-2.out.log
stderr_logfile=/var/log/redis/redis-cluster-master-2.err.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stopsignal=TERM

[program:redis-cluster-slave-0]
command=/usr/local/bin/redis-server /etc/redis/redis.conf --protected-mode no --bind 0.0.0.0 --port 6383 --cluster-config-file 6383.conf --dbfilename dump-6383.rdb --appendfilename aof.6383.base.rdb
autostart=true
autorestart=true
priority=103
stdout_logfile=/var/log/redis/redis-cluster-slave-0.out.log
stderr_logfile=/var/log/redis/redis-cluster-slave-0.err.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stopsignal=TERM

[program:redis-cluster-slave-1]
command=/usr/local/bin/redis-server /etc/redis/redis.conf --protected-mode no --bind 0.0.0.0 --port 6384 --cluster-config-file 6384.conf --dbfilename dump-6384.rdb --appendfilename aof.6384.base.rdb
autostart=true
autorestart=true
priority=104
stdout_logfile=/var/log/redis/redis-cluster-slave-1.out.log
stderr_logfile=/var/log/redis/redis-cluster-slave-1.err.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stopsignal=TERM

[program:redis-cluster-slave-2]
command=/usr/local/bin/redis-server /etc/redis/redis.conf --protected-mode no --bind 0.0.0.0 --port 6385 --cluster-config-file 6385.conf --dbfilename dump-6385.rdb --appendfilename aof.6385.base.rdb
autostart=true
autorestart=true
priority=105
stdout_logfile=/var/log/redis/redis-cluster-slave-2.out.log
stderr_logfile=/var/log/redis/redis-cluster-slave-2.err.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stopsignal=TERM
