#port 26379
#bind 127.0.0.1
protected-mode no
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor default_service redis-primary 6379 1
sentinel down-after-milliseconds default_service 3200
sentinel failover-timeout default_service 10000
sentinel parallel-syncs default_service 1
#sentinel announce-ip 127.0.0.1
